### ISSUE TITLE
Content property shouldn't always be required

### ISSUE THREAD

**Issue by terminalpixel** [voxpelli/node-micropub-express#1]
Hi there, 

I recently was having issues with posting from https://teacup.p3k.io as it does not send a content property.

And this library requires a value at index.js#L252, I manually got it working by just making it `if (!data.properties)` but I don't know if that's the best option or not.

**Comment by voxpelli** [comment]
I agree. Should probably remove the content validation from the endpoint and leave it to the handler to decide whether or not it knows how to handle the content. Will fix.

(And sorry for not responding earlier, GitHub notifications are so easy to miss :stuck_out_tongue:)

**Comment by voxpelli** [comment]
Fixed it the same way that you did – so it still checks that there are at least some properties, but it no longer cares what those properties actually are. Thanks for suggesting it!
