### ISSUE TITLE
Syndication Target Draft Spec Changed

### ISSUE THREAD

**Issue by miklb** [voxpelli/node-micropub-express#3]
I'm working my way through this, and when I figure it out I will hopefully be able to add a pull request but wanted to share that checking with @aaronpk in IRC, he pointed out Quill matches with the current spec, specifically for [syndication-target](http://micropub.net/draft/#syndication-targets) requiring passing an `uid` and `name`.

If I'm deciphering the code correctly, node-micropub-express needs to be able to handle both params in the queryHandler. Am I on the right path?

**Comment by voxpelli** [comment]
The support in this module was solved by #2 by adding a generic support for queries, so the user of this module can support any query – including `syndicate-to` – by adding a `queryHandler` in their project when configuring this module.

So, in terms of the "glue" project, it would be added as another options key besides the existing `handler` option here: https://github.com/voxpelli/webpage-micropub-to-github/blob/master/lib/main.js#L46

The `queryHandler` will be sent two arguments: The query string, so in this case `syndicate-to`, and the request object, which isn't necessary to use in all projects, but which in the "glue" project enables finding the site configuration through `req.targetsite`.

A quick sketch of a query handler would be:

```javascript
queryHandler: function (q, req) {
  if (q === 'syndicate-to' && req.targetsite.syndicateTo) {
    return { 'syndicate-to': req.targetsite.syndicateTo };
  }
}
```

**Comment by miklb** [comment]
That part I basically had sorted, it was the part on how to pass both parameters in the syndicateTo portion.

**Comment by miklb** [comment]
OK, color me embarrassed. That works just fine with both parameters of `uid` and `name`. That or something changed on Quill. 

Cheers, thanks again for sharing all of this.
