### ISSUE TITLE
Support space-separated list of scopes

### ISSUE THREAD

**Issue by richardcarls** [voxpelli/node-micropub-express#4]
I default to using a space-delineated string, which I think is pretty standard but not explicitly required. https://indieauth.com, for example will just pass on whatever you supply in the request, but the auth screen splits scope on a space to show the list of requested scopes.

**Comment by voxpelli** [comment]
I'll have to look into this, would have been great if there was a standard, but I can't remember either if there are. Maybe @aaronpk knows?

**Comment by richardcarls** [comment]
http://micropub.net/draft/#authentication-and-authorization

5.4 Scope
The client may request one or more scopes during the authorization request. It does this according to standard OAuth 2.0 techniques, by passing **a space-separated list of scope names** in the authorization request. [RFC6749]
